# model/tokenizer
model_name: "decapoda-research/llama-7b-hf"
tokenizer_name: "decapoda-research/llama-7b-hf"
gradient_checkpointing: true  # org
save_name: "nomic-ai/gpt4all-full-multi-turn"
# gradient_checkpointing: false

# dataset
streaming: false
num_proc: 64
dataset_path: train_data/ko_alpaca_data_5000.json # update
max_length: 1024
batch_size: 32

# train dynamics
lr: 5.0e-5
eval_every: 800
eval_steps: 100
save_every: 800
output_dir: "ckpts/gpt4all-full-multi"
checkpoint: null
lora: false
warmup_steps: 100
num_epochs: 2

# logging
wandb: false
wandb_entity: # update
wandb_project_name: # update
seed: 42

